ALTER TABLE workers ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS hidden_note TEXT;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS hidden_at TIMESTAMPTZ;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS hidden_by TEXT;
